#!/usr/bin/env python3
'''
Get title for usage in my RSS scripts for newsboat
'''

from sys import argv
from urllib.request import urlopen
from re import search,IGNORECASE 

def get_title(url:str) -> str:
    content = urlopen(url).read().decode('UTF-8')
    return search('<\W*title\W*(.*)</title', content, IGNORECASE).group(1)


if __name__ == '__main__':

    title = get_title(argv[1])
    if title.endswith('- YouTube'):
        title = title[:title.find('- YouTube')]
    print(title)
