#!/usr/bin/env python3
'''
Get title for usage in my RSS scripts for newsboat
'''

from sys import argv
from re import search,IGNORECASE 
from requests import get

def get_title(url:str) -> str:
    return search('<\W*title\W*(.*)</title', get(url).text, IGNORECASE).group(1)


if __name__ == '__main__':

    title = get_title(argv[1])
    if title.endswith('- YouTube'):
        title = title[:title.find('- YouTube')]
    print(title)
